mark_task_complete:
  name: Mark Task Complete
  description: Mark a task as completed
  fields:
    task_id:
      name: Task ID
      description: The ID of the task to mark as complete
      required: true
      selector:
        text:

create_task:
  name: Create Task
  description: Create a new task
  fields:
    name:
      name: Task Name
      description: Name of the task
      required: true
      selector:
        text:
    schedule_mode:
      name: Schedule Mode
      description: How the task is scheduled
      required: true
      selector:
        select:
          options:
            - value: fixed_date
              label: Fixed Date
            - value: fixed_occurrence
              label: Fixed Occurrence
            - value: fixed_interval
              label: Fixed Interval
    interval_days:
      name: Interval Days
      description: Number of days for interval scheduling
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: days
    interval_mode:
      name: Interval Mode
      description: How the interval is calculated
      selector:
        select:
          options:
            - value: hard_fixed
              label: Hard Fixed
            - value: after_completion
              label: After Completion
    enabled:
      name: Enabled
      description: Whether the task is enabled
      default: true
      selector:
        boolean:

delete_task:
  name: Delete Task
  description: Delete a task
  fields:
    task_id:
      name: Task ID
      description: The ID of the task to delete
      required: true
      selector:
        text:

update_task:
  name: Update Task
  description: Update a task
  fields:
    task_id:
      name: Task ID
      description: The ID of the task to update
      required: true
      selector:
        text:
    name:
      name: Task Name
      description: New name of the task
      selector:
        text:
    enabled:
      name: Enabled
      description: Whether the task is enabled
      selector:
        boolean:
